version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data
    tables:
      - name: sales
        freshness:
          warn_after:
            count:  90
            period: day
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        identifier: raw_gz_sales
        description: revenues and quantity per orders
        columns:
          - name: CONCAT(pdt_id, '_', orders_id)
            description: primary key of product table
            tests:
              - unique
              - not_null
      - name: product
        identifier : raw_gz_product
        description: purchase price by product id
        columns:
          - name: products_id
            description: primary key of product table
            tests:
              - unique
              - not_null
      - name: ship
        identifier : raw_gz_ship
        description: shipping and log cost by order id
        columns:
          - name: orders_id
            description: primary key of ship the table
            tests:
              - unique
              - not_null